plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}

group = 'com.demo'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.json:json:20240303'
    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'com.demo.Main'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.demo.Main'
        )
    }
}

test {
    useJUnit()
    finalizedBy jacocoTestReport

    jacocoTestReport {
        dependsOn test

        reports {
            xml.required = false
            csv.required = false
            html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
        }
    }
}